language: cpp
sudo: required
dist: trusty

compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++ libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev libminiupnpc-dev libqt4-dev libqrencode-dev qt4-qmake
    
script:
    - qmake "USE_DBUS=1" "USE_QRCODE=1" "USE_UPNP=1"
    - make
    - make check